package com.sheout.users.internal;

public enum CustomerProfileError {
    PROFILE_NOT_FOUND,
    CONTACT_NOT_FOUND,
    PHOTO_STORAGE_FAILED,
    PROFILE_PHOTO_REQUIRED,
    DATE_OF_BIRTH_REQUIRED,
    INVALID_DATE_OF_BIRTH,
    UNDER_MINIMUM_AGE,
    INVALID_EMAIL
}
