-- 1. A short code for every product, e.g. 7K9M2XQ.
--
-- A customer who messages a seller about "the blue saree" leaves her
-- guessing which one; a code in the message does not. Seven characters from
-- an alphabet without the look-alikes 0/O and 1/I/L, so it can be read out
-- on a call and typed back without mistakes. Generated by the app for new
-- products (ProductCodes); the products that already exist get one here.
alter table seller_products add column code varchar(8);

do $$
declare
    alphabet constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
    r record;
    candidate text;
begin
    for r in select id from seller_products where code is null loop
        loop
            candidate := '';
            for i in 1..7 loop
                candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
            end loop;
            exit when not exists (select 1 from seller_products where code = candidate);
        end loop;
        update seller_products set code = candidate where id = r.id;
    end loop;
end $$;

alter table seller_products alter column code set not null;
create unique index ux_seller_products_code on seller_products (code);

-- 2. The price before a discount, shown struck through above the price.
-- Optional; when set the app requires it to be above display_price. That
-- it was a real earlier price is the seller's declaration, not checked here.
alter table seller_products add column original_price numeric(10, 2);

-- 3. A seller's own website, shown on her listing. Validated as an http(s)
-- address by the app.
alter table seller_profiles add column website_url varchar(200);

-- 4. Marketplace searches "in your own words" go through the same model and
-- the same daily usage row as SheOut Help; they are counted separately so
-- each has its own cap, and their tokens add to the same cost figures.
alter table assistant_usage add column searches integer not null default 0;
